apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app   # everything will be created in this namespace automatically

resources:
  # Namespace must be applied first
  - namespace.yaml

  # Storage resources
  - storageclass.yaml
  - pv.yaml
  - pvc.yaml

  # Secrets and ConfigMaps
  - secret.yaml
  - configmap.yaml

  # Workloads
  - deployment.yaml
  - hpa.yaml
  - service.yaml
  - ingress.yaml
